### PRODUTOS

GET http://localhost:3333/products

###
GET http://localhost:3333/products?name=batata

###
POST http://localhost:3333/products
Content-Type: application/json

{
    "name": "Porção de Isca de Peixe",
    "price": 60.00
}

### 
PUT http://localhost:3333/products/1
Content-Type: application/json

{
    "name": "Porção de batata",
    "price": 40.00
}

###
DELETE http://localhost:3333/products/1

### MESAS

GET http://localhost:3333/tables


### SESSÃO DAS MESAS

POST http://localhost:3333/tables-sessions
Content-Type: application/json

{
    "table_id": 1
}

###
GET http://localhost:3333/tables-sessions

###
PATCH http://localhost:3333/tables-sessions/3

### orders

POST http://localhost:3333/orders
Content-Type: application/json

{
    "table_session_id": 1,
    "product_id": 1,
    "quantity": 2
}

###
GET http://localhost:3333/orders/table-session/1


###
GET http://localhost:3333/orders/table-session/1/total